spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/carmanagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Yasindu20$

# Updated database dialect to MySQL8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080

# Logging levels for debugging
logging.level.org.springframework.web=DEBUG
logging.level.com.example.computer_item_repair=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Allow bean overriding
spring.main.allow-bean-definition-overriding=true

# Debug Spring Boot startup
debug=true
logging.level.org.springframework.boot.autoconfigure=DEBUG